server:
  port: 8081
  tomcat:
    threads:
      max: 256

http:
  client:
    connectionTimeout: 3000
    readTimeout: 7000
    maxConnection: 50
    maxConnPerRoute: 10

naver:
  openapi:
    movieUrl: https://openapi.naver.com/v1/search/movie.json
    clientId: B9ABOSMvv55TVjeoqQD6
    clientSecret: s9Z0H1vi_9